In [1]:
# Import TensorFlow Module
import tensorflow as tf

# Import the sys module to get the version of Python
from sys import version as ver

In [2]:
## Example #1
## Basic Constant Variable Definition and Print Function

# Define some constants
a = tf.constant(3)
b = tf.constant(5)

# Do some basic math and print the result using the with...as... statement
# Note that since I am using Python 3.5.2 not 2.7, the usage of the print function is slightly different
with tf.Session() as sess:
    print('Python version used', ver)
    print("a = {0:1d}, b = {1:1d}".format(sess.run(a), sess.run(b)))
    print("a + b = {0:2d}".format(sess.run(a+b)))
    print("a * b = {0:2d}".format(sess.run(a*b)))

Python version used 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
a = 3, b = 5
a + b =  8
a * b = 15


In [3]:
## Example #2
## Basic Operations with Placeholder function

# Initialize a, b as two integer placeholders (i.e. variables)
a = tf.placeholder(tf.int32, name="var_a")
b = tf.placeholder(tf.int32, name="var_b")

# Now you can define some arbitrary operations
opAdd = tf.add(a, b)
opSub = tf.sub(a, b)
opMul = tf.mul(a, b)

# Print the result (Note the difference with example #1)
with tf.Session() as sess:
    print(
        "a = {0}, b = {1}".format(
            sess.run(a, feed_dict={a: 3}), 
            sess.run(b, feed_dict={b: 5})))
    print("a + b = {0}".format(sess.run(opAdd, feed_dict={a: 3, b: 5})))
    print("a - b = {0}".format(sess.run(opSub, feed_dict={a: 3, b: 5})))
    print("a * b = {0}".format(sess.run(opMul, feed_dict={a: 3, b: 5})))

a = 3, b = 5
a + b = 8
a - b = -2
a * b = 15


In [4]:
## Example #3
## Simple Matrix Operations

# Create two constant matrix with a dimension of 3x3
mat1 = tf.constant([[1., 2., 3.],
                    [4., 5., 6.],
                    [7., 8., 9.]])
mat2 = tf.constant([[9., 8., 7.],
                    [6., 5., 4.],
                    [3., 2., 1.]])

# Run some simple matrix operation
opAdd = mat1 + mat2;
opSub = mat1 - mat2;
opMul = tf.matmul(mat1, mat2)

# Print the results
with tf.Session() as sess:
    print("Addition: \n", sess.run(opAdd),"\n")
    print("Subtraction : \n", sess.run(opSub),"\n")
    print("Multiplication: \n", sess.run(opMul),"\n")

Addition: 
 [[ 10.  10.  10.]
 [ 10.  10.  10.]
 [ 10.  10.  10.]] 

Subtraction : 
 [[-8. -6. -4.]
 [-2.  0.  2.]
 [ 4.  6.  8.]] 

Multiplication: 
 [[  30.   24.   18.]
 [  84.   69.   54.]
 [ 138.  114.   90.]] 

